{% set name = "pot" %}
{% set version = "0.9.6.post1" %}
{% set sha256 = "9b6cc14a8daecfe1268268168cf46548f9130976b22b24a9e8ec62a734be6c43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [python_impl == 'pypy']
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=0.23
    - numpy
  run:
    - python
    - numpy
    - scipy >=1.0
    - matplotlib-base >=1.5

test:
  imports:
    - ot

about:
  home: http://github.com/PythonOT/POT
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Optimal Transport library
  description: |
    This open source Python library provide several solvers for optimization
    problems related to Optimal Transport for signal, image processing and
    machine learning.
  doc_url: https://pythonot.github.io/
  dev_url: https://github.com/PythonOT/POT

extra:
  recipe-maintainers:
    - djsutherland
    - rflamary
